# -*- coding: utf-8 -*-
"""Bản sao của S5_MC4AI_ASM.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1W8Td1djoYuxgtOIIrBgbKr95RJYQ0j4U

<h1><center>

<img src="https://i.imgur.com/LSeMSbh.jpg" alt="logo" width="700" height="300">
<h1><b>SESSION 5 - LINEAR REGRESSION</b></h1>

</center></h1>

<h1><b><center>ƯỚC LƯỢNG DOANH THU CỦA MỘT CÔNG TY BÁN KEM DỰA VÀO NHIỆT ĐỘ TRONG THÁNG</center></b></h1>

#**Create Data**

Tạo short-cut đến [**dataset**](https://drive.google.com/file/d/1wZETgqcnl0dQJ8FV3hI_Y64LK1KNfGyE/view?usp=share_link) từ Google Drive rồi chạy các cell code dưới đây để tạo data
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np

df = pd.read_csv('/content/drive/MyDrive/IceCreamData.csv')
df.head()

x = df['Temperature'].values
y = df['Revenue'].values

from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(x, y)
import pickle

filename = 'model.pickle'

pickle.dump(model, open(filename, "wb"))
model = pickle.load(open(filename, "rb"))



"""#**TODO: Visualize Data**

Scatter các điểm (x,y)
"""

# YOUR CODE HERE

"""#**TODO: Split Data**

Tách tập dữ liệu (x,y) thành 2 tập train, test bằng thư viện **scikit-learn** ([document](https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.train_test_split.html)) sao cho tập test có 50 sample. In ra shape của các tập dữ liệu để biết kết quả
"""

# YOUR CODE HERE

"""Scatter lại 2 tập train, test (2 tập 2 màu khác nhau)"""

# YOUR CODE HERE

"""#**TODO: Create, Train, Evaluate**

Tạo và fit model trên tập train (chú ý shape)
"""

# YOUR CODE HERE

"""**Weights**"""

# YOUR CODE HERE

"""**Evaluate:** đánh giá model trên tập test"""

# YOUR CODE HERE

"""#**TODO: Regression Line**

Scatter lại tập (x,y) và plot Regression Line
"""

# YOUR CODE HERE

"""#**TODO: Save Model**"""

# YOUR CODE HERE

"""#**TODO: Deploy Streamlit App**

Tạo ứng dụng Streamlit (dùng Streamlit Cloud) cho phép người dùng nhập vào nhiệt độ, xuất ra doanh thu dự báo trong tháng

<center>
<img src="https://i.imgur.com/StAakCD.png"height="300">
<h1>
</center>

![]()

**Lưu ý:**
- Có thể tạo repository mới (đặt tên tuỳ ý) hoặc dùng lại repository cũ (`my-first-streamlit-app`)
- Download file model đã lưu ở trên rồi upload lên repository, sau đó load lại model (bằng thư viện pickle) để dùng cho predict
- requirements.txt
```



